// Generated by ReScript, PLEASE EDIT WITH CARE


let Env = {};

let Request = {};

let Response = {};

let HttpServer = {};

let Http = {};

let Crypto = {};

let $$ArrayBuffer = {};

let Base64 = {};

let TextEncoder = {};

let TextDecoder = {};

let Fetch = {};

export {
  Env,
  Request,
  Response,
  HttpServer,
  Http,
  Crypto,
  $$ArrayBuffer,
  Base64,
  TextEncoder,
  TextDecoder,
  Fetch,
}
/* No side effect */
