// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let userAgent = "oikos-bot/0.1.0-beta";

let apiVersion = "2022-11-28";

async function apiRequest(token, method, endpoint, body) {
  let url = `https://api.github.com` + endpoint;
  let headers = {
    Authorization: `Bearer ` + token,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": apiVersion,
    "User-Agent": userAgent,
    "Content-Type": "application/json"
  };
  try {
    let response = body !== undefined ? await globalThis.fetch(url, {
        method: method,
        headers: headers,
        body: JSON.stringify(body)
      }) : await globalThis.fetch(url, {
        method: method,
        headers: headers
      });
    if (response.ok) {
      let json = await response.json();
      return {
        TAG: "Ok",
        _0: json
      };
    }
    let status = response.status;
    let errorBody = await response.text();
    return {
      TAG: "Error",
      _0: `GitHub API error ` + String(status) + `: ` + errorBody
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    let jsExn = Stdlib_Exn.asJsExn(exn);
    let msg = jsExn !== undefined ? Belt_Option.getWithDefault(Primitive_option.valFromOption(jsExn).message, "Unknown error") : "Unknown error";
    return {
      TAG: "Error",
      _0: `API request failed: ` + msg
    };
  }
}

async function postPRComment(token, owner, repo, prNumber, body) {
  let endpoint = `/repos/` + owner + `/` + repo + `/issues/` + String(prNumber) + `/comments`;
  let payload = Js_dict.fromArray([[
      "body",
      body
    ]]);
  let result = await apiRequest(token, "POST", endpoint, payload);
  if (result.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: result._0
    };
  }
  let obj = Js_json.decodeObject(result._0);
  if (obj === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid JSON response"
    };
  }
  let id = Js_dict.get(obj, "id");
  if (id === undefined) {
    return {
      TAG: "Error",
      _0: "No comment ID in response"
    };
  }
  let num = Js_json.decodeNumber(id);
  if (num !== undefined) {
    return {
      TAG: "Ok",
      _0: num | 0
    };
  } else {
    return {
      TAG: "Error",
      _0: "Invalid comment ID in response"
    };
  }
}

async function updateComment(token, owner, repo, commentId, body) {
  let endpoint = `/repos/` + owner + `/` + repo + `/issues/comments/` + String(commentId);
  let payload = Js_dict.fromArray([[
      "body",
      body
    ]]);
  let result = await apiRequest(token, "PATCH", endpoint, payload);
  if (result.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: result._0
    };
  }
}

async function createCheckRun(token, owner, repo, headSha, name, conclusion, title, summary) {
  let endpoint = `/repos/` + owner + `/` + repo + `/check-runs`;
  let payload = Js_dict.fromArray([
    [
      "name",
      name
    ],
    [
      "head_sha",
      headSha
    ],
    [
      "status",
      "completed"
    ],
    [
      "conclusion",
      conclusion
    ],
    [
      "output",
      Js_dict.fromArray([
        [
          "title",
          title
        ],
        [
          "summary",
          summary
        ]
      ])
    ]
  ]);
  let result = await apiRequest(token, "POST", endpoint, payload);
  if (result.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: result._0
    };
  }
  let obj = Js_json.decodeObject(result._0);
  if (obj === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid JSON response"
    };
  }
  let id = Js_dict.get(obj, "id");
  if (id === undefined) {
    return {
      TAG: "Error",
      _0: "No check run ID in response"
    };
  }
  let num = Js_json.decodeNumber(id);
  if (num !== undefined) {
    return {
      TAG: "Ok",
      _0: num | 0
    };
  } else {
    return {
      TAG: "Error",
      _0: "Invalid check run ID in response"
    };
  }
}

async function getPullRequest(token, owner, repo, prNumber) {
  let endpoint = `/repos/` + owner + `/` + repo + `/pulls/` + String(prNumber);
  return await apiRequest(token, "GET", endpoint, undefined);
}

async function getRepository(token, owner, repo) {
  let endpoint = `/repos/` + owner + `/` + repo;
  return await apiRequest(token, "GET", endpoint, undefined);
}

export {
  userAgent,
  apiVersion,
  apiRequest,
  postPRComment,
  updateComment,
  createCheckRun,
  getPullRequest,
  getRepository,
}
/* No side effect */
