// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

async function verifyGitHubSignature(payload, signature, secret) {
  let encoder = new (globalThis.TextEncoder)();
  let keyData = encoder.encode(secret);
  let data = encoder.encode(payload);
  let key = await globalThis.crypto.subtle.importKey("raw", keyData, {
    name: "HMAC",
    hash: "SHA-256"
  }, false, [
    "sign",
    "verify"
  ]);
  let signatureBytes = encoder.encode(Js_string.replace("sha256=", "", signature));
  return await globalThis.crypto.subtle.verify("HMAC", key, signatureBytes, data);
}

function verifyGitLabToken(token, secret) {
  return token === secret;
}

function parseGitHubEvent(headers, payload) {
  let eventType = Js_dict.get(headers, "x-github-event");
  let obj = Js_json.decodeObject(payload);
  let action;
  if (obj !== undefined) {
    let a = Js_dict.get(obj, "action");
    action = a !== undefined ? Js_json.decodeString(a) : undefined;
  } else {
    action = undefined;
  }
  if (eventType === undefined) {
    return;
  }
  let obj$1 = Js_json.decodeObject(payload);
  let repo;
  if (obj$1 !== undefined) {
    let r = Js_dict.get(obj$1, "repository");
    if (r !== undefined) {
      let repoObj = Js_json.decodeObject(r);
      if (repoObj !== undefined) {
        let o = Js_dict.get(repoObj, "owner");
        let owner;
        if (o !== undefined) {
          let ownerObj = Js_json.decodeObject(o);
          if (ownerObj !== undefined) {
            let l = Js_dict.get(ownerObj, "login");
            owner = l !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(l), "") : "";
          } else {
            owner = "";
          }
        } else {
          owner = "";
        }
        let n = Js_dict.get(repoObj, "name");
        let name = n !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(n), "") : "";
        let u = Js_dict.get(repoObj, "html_url");
        let url = u !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(u), "") : "";
        repo = {
          owner: owner,
          name: name,
          url: url
        };
      } else {
        repo = undefined;
      }
    } else {
      repo = undefined;
    }
  } else {
    repo = undefined;
  }
  if (repo !== undefined) {
    return {
      platform: "GitHub",
      eventType: eventType,
      action: action,
      repository: repo,
      payload: payload
    };
  }
}

function parseGitLabEvent(headers, payload) {
  let eventType = Js_dict.get(headers, "x-gitlab-event");
  if (eventType === undefined) {
    return;
  }
  let obj = Js_json.decodeObject(payload);
  let repo;
  if (obj !== undefined) {
    let p = Js_dict.get(obj, "project");
    if (p !== undefined) {
      let projObj = Js_json.decodeObject(p);
      if (projObj !== undefined) {
        let n = Js_dict.get(projObj, "namespace");
        let namespace = n !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(n), "") : "";
        let n$1 = Js_dict.get(projObj, "name");
        let name = n$1 !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(n$1), "") : "";
        let u = Js_dict.get(projObj, "web_url");
        let url = u !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(u), "") : "";
        repo = {
          owner: namespace,
          name: name,
          url: url
        };
      } else {
        repo = undefined;
      }
    } else {
      repo = undefined;
    }
  } else {
    repo = undefined;
  }
  if (repo !== undefined) {
    return {
      platform: "GitLab",
      eventType: eventType,
      action: undefined,
      repository: repo,
      payload: payload
    };
  }
}

export {
  verifyGitHubSignature,
  verifyGitLabToken,
  parseGitHubEvent,
  parseGitLabEvent,
}
/* No side effect */
